{% set version = "2.0.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-multipanelfigure
  version: {{ version|replace("-", "_") }}

source:
  fn: multipanelfigure_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/multipanelfigure_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multipanelfigure/multipanelfigure_{{ version }}.tar.gz
  sha256: 47b04774f10ce11d57298af76b7e2e7c27545ccfa815131b63c99bae2b584438

build:
  merge_build_host: True  # [win]
  number: 0
  # no r-magick package for win64
  skip: true  # [win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-assertive.base >=0.0_7
    - r-assertive.files >=0.0_2
    - r-assertive.numbers >=0.0_2
    - r-assertive.properties >=0.0_4
    - r-assertive.types >=0.0_3
    - r-ggplot2 >=2.2.1
    - r-gridgraphics >=0.3_0
    - r-gtable >=0.2.0
    - r-magick >=1.9
    - r-magrittr >=1.5
    - r-stringi >=1.2.3
  run:
    - r-base
    - r-assertive.base >=0.0_7
    - r-assertive.files >=0.0_2
    - r-assertive.numbers >=0.0_2
    - r-assertive.properties >=0.0_4
    - r-assertive.types >=0.0_3
    - r-ggplot2 >=2.2.1
    - r-gridgraphics >=0.3_0
    - r-gtable >=0.2.0
    - r-magick >=1.9
    - r-magrittr >=1.5
    - r-stringi >=1.2.3

test:
  commands:
    - $R -e "library('multipanelfigure')"           # [not win]
    - "\"%R%\" -e \"library('multipanelfigure')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=multipanelfigure
  license: GPL (>= 3)
  summary: Tools to create a layout for figures made of multiple panels, and to fill the panels
    with base, 'lattice', 'ggplot2' and 'ComplexHeatmap' plots, grobs, as well as content
    from all image formats supported by ImageMagick (accessed through 'magick').
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - jenzopr
