{% set version = "2.1.6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-multipanelfigure
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/multipanelfigure_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/multipanelfigure/multipanelfigure_{{ version }}.tar.gz
  sha256: fbbc190cb7af5ddaefafcedc51fad1c8bb7b97a27c8d812f57b2ebd2ae836538

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-assertive.base >=0.0_7
    - r-assertive.files >=0.0_2
    - r-assertive.numbers >=0.0_2
    - r-assertive.properties >=0.0_4
    - r-assertive.types >=0.0_3
    - r-ggplot2 >=2.2.1
    - r-gridgraphics >=0.3_0
    - r-gtable >=0.2.0
    - r-magick >=1.9
    - r-magrittr >=1.5
    - r-stringi >=1.2.3
  run:
    - r-base
    - r-assertive.base >=0.0_7
    - r-assertive.files >=0.0_2
    - r-assertive.numbers >=0.0_2
    - r-assertive.properties >=0.0_4
    - r-assertive.types >=0.0_3
    - r-ggplot2 >=2.2.1
    - r-gridgraphics >=0.3_0
    - r-gtable >=0.2.0
    - r-magick >=1.9
    - r-magrittr >=1.5
    - r-stringi >=1.2.3

test:
  commands:
    - $R -e "library('multipanelfigure')"           # [not win]
    - "\"%R%\" -e \"library('multipanelfigure')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=multipanelfigure
  license: GPL (>= 3)
  summary: Tools to create a layout for figures made of multiple panels, and to fill the panels with base, 'lattice', 'ggplot2' and 'ComplexHeatmap' plots, grobs, as well as content from all image formats supported by 'ImageMagick' (accessed through 'magick').
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - jenzopr

# Package: multipanelfigure
# Type: Package
# Title: Infrastructure to Assemble Multi-Panel Figures (from Grobs)
# Version: 2.0.2
# Date: 2019-01-14
# Author: Johannes Graumann [cre, aut], Richard Cotton [ctb]
# Maintainer: Johannes Graumann <johannes.graumann@mpi-bn.mpg.de>
# Authors@R: c(person("Johannes", "Graumann", email = "johannes.graumann@mpi-bn.mpg.de", role = c("cre", "aut")), person("Richard","Cotton", email = "richierocks@gmail.com", role = c("ctb")))
# Description: Tools to create a layout for figures made of multiple panels, and to fill the panels with base, 'lattice', 'ggplot2' and 'ComplexHeatmap' plots, grobs, as well as content from all image formats supported by 'ImageMagick' (accessed through 'magick').
# Imports: assertive.base (>= 0.0-7), assertive.files (>= 0.0-2), assertive.numbers (>= 0.0-2), assertive.properties (>= 0.0-4), assertive.types (>= 0.0-3), ggplot2 (>= 2.2.1), grid, gridGraphics (>= 0.3-0), gtable (>= 0.2.0), magick (>= 1.9), magrittr (>= 1.5), stats, stringi (>= 1.2.3), utils
# Suggests: ComplexHeatmap (>= 1.17.1), grDevices, lattice (>= 0.20-35), roxygen2 (>= 6.0.1), VennDiagram (>= 1.6.20), knitr, rmarkdown, markdown
# License: GPL (>= 3)
# RoxygenNote: 6.1.1
# LazyData: TRUE
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-01-14 13:13:27 UTC; balin
# Repository: CRAN
# Date/Publication: 2019-01-14 13:30:02 UTC
