appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pp91s4geUWXOL+kDPJk3QNoy5uEU3lUd0+XEZmZkFRSHueY3wTkzh8iSL8gDWob+r+DXU9MX+jO7QV6v1cVaeDkiOV/6XkhemAS4LJhyGixS0x4MQJKHEqbpK/Xcac2bUHGGI2/Pa8i7BPaL4YQv8iQvWPx96NUxrpXxr3dO/MupV8rtQM5qHitlkJ6zLKGgpbEO+amJd4q/h4J2sQtC0+m4DcVJTHxE9+Dn8o2kDXT7hrIWUhMU6YNgMH69s5iZ5pmcjei6WqIRoIsVG1ZQq3+7R3xNj+lZaxNXeOsagH/FvMxr+H03gmRsEaqYmnofjqAn9Wf/L9eSkDEy9gNue9k4ktKa4pb1VvW4Cl76Rs/A1ZxyuGC1pc1bAqcsCqegdzT5KCnVBR81pzDoO7gb/QeqdQpBV0+evgja++fvfWmrbNULE9anyLkyX1ah6mzCSq4+pu3EbocCmXdtPcVqWXQxN/51LAq2Oq8sO3lxYXHwAaRsnjC9ibD1XP3AoH8obVj1wk/JZf53ccVfhHMGN3RhjaFThLOvjnKe7RmU9o+JPGa6md7eY/QZ8oDBB2uS0hKYIpx2a6FEcTNQOt746u0xxXv1W+Xg8we8z4Lt5WZNihpUK/TTYq+tkk8EwwP+MCYsvLWPF2ttGSWCzOKdpKj3kADyQvQxuO5uaeBFx0M=
