travis:
  secure:
    BINSTAR_TOKEN: ZzZs9A1KqtVqPbr4AiUuhGEvpzlP26ZF1sPb/LiPMVQ/N7aWZMGvLeBiAhfwV3UE0nh4dmRXaeHsSNWb/D7LHqrD6R0irLdZWa8xz9n9r0ESyQjcJVLyIQcOm2fSmpxwaHO3SkNqMWbUP86nBchmbiC8WSJOYKVloS+YgBaUUVJHcHKx+TOhczd+9sjbK2dvFWgVyKYNGlW/4VBWjCdJ2GkYKno4+SWuwyc7pITdR00zwshQSGWSUMRAquV+t+kmIyB9bJnNQR8ltzjylgr/09vO1aweBcPQy7AbQYqTrGwtHiXrD/oRWMAlulYxT59/rOrC+YgSjMsbYGgLCvLSZnKSknFtpj9wtILPJktx/SdWg6FKPGus7BHogyffFs6kV77VN9f7ex1tnm9esq0byzo7pfgmZAyTzB1PauGmmRqZ6ePWIQIz9HDcF3MFcp+G7yhyIyl7puKOvilkN9oS8hNXt8HIdUqjMIyF4KVCTIG4rt7Pa3Hi3vZtSLo5031R9c2eLVs583kPAXvGZTjSSqSKlM6XSckTaYztQynSmyFUuOKf3TZQl6TuI9STbJVXXPwmBJBGJYjsdCVLQSLPKb3Lh/SzwV8j5Dlf6JbrU16z4OMM+tLcRmxlmAnJH9/JlA95y+7AQSqG5KZwfA9Qltk346RiZbCvRf0hba2DGJE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
